outdir: babappasnake_run
outgroup_query: ""
iqtree_model: "MFP"
iqtree_bootstrap: 1000
iqtree_bnni: false
absrel_branches: "Leaves"
meme_branches: "Leaves"
codeml_codonfreq: 2
use_clipkit: true
clipkit_mode_protein: "kpic-smart-gap"
clipkit_mode_codon: "kpic-smart-gap"
absrel_dynamic_start: 0.05
absrel_dynamic_step: 0.01
absrel_dynamic_max: 1.0
